services:
  - type: web
    name: pi-boom
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: MODE
        value: cloud
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
