/**
 * Development work by David Lane
 */
import { Router } from 'express';
import buildAudioRoutes from './audio.routes.js';
import voiceRoutes from './voice.routes.js';
import musicResearchRoutes from './music-research.routes.js';
import chatRoutes from './chat.routes.js';
import albumDiscoveryRoutes from './album-discovery.routes.js';
import treeDiscoveryRoutes from './tree-discovery.routes.js';
import treeCollectionRoutes from './tree-collection.routes.js';
import critterDiscoveryRoutes from './critter-discovery.routes.js';
import critterCollectionRoutes from './critter-collection.routes.js';
import natureCollectionRoutes from './nature-collection.routes.js';
import blacklightRoutes from './blacklight.routes.js';
import ouijaBoardRoutes from './ouija-board.routes.js';
import spotifyRoutes from './spotify.routes.js';
import collectionRoutes from './collection.routes.js';
import musicHistoryRoutes from './music-history.routes.js';
import posterGeneratorRoutes from './poster-generator.routes.js';
import voiceDjRoutes from './voice-dj.routes.js';
import genealogyRoutes from './genealogy.routes.js';
import audioFingerprintRoutes from './audio-fingerprint.routes.js';
import sampleDetectionRoutes from './sample-detection.routes.js';
import encompassAssistantRoutes from './encompass-assistant.routes.js';
import kmlRoutes from './kml.routes.js';
import gratefulDeadTourRoutes from './grateful-dead-tour.routes.js';
import musicPilgrimageRoutes from './music-pilgrimage.routes.js';
import userShowAttendanceRoutes from './user-show-attendance.routes.js';
import concertCollectionRoutes from './concert-collection.routes.js';
import loanPipelineRoutes from './loan-pipeline.routes.js';
import disastersRoutes from './disasters.routes.js';
import encompassHubRoutes from './encompass-hub.routes.js';
import encompassWebhookRoutes from './encompass-webhook.routes.js';
import fishCatchesRoutes from './fish-catches.routes.js';
import rockDiscoveryRoutes from './rock-discovery.routes.js';
import rockCollectionRoutes from './rock-collection.routes.js';
import bikesRoutes from './bikes.routes.js';
import customersRoutes from './customers.routes.js';
import unitTestsRoutes from './unit-tests.routes.js';
import reviewerRoutes from './reviewer.routes.js';
import localSpotsRoutes from './local-spots.routes.js';
import findsRoutes from './finds.routes.js';
import appUserAuthRoutes from './app-user-auth.routes.js';
import gseRoutes from './gse.routes.js';
import financeRoutes from './finance.routes.js';
import disasterImpactGraphRoutes from './disaster-impact-graph.routes.js';

export default function buildRoutes(io) {
  const api = Router();
  api.use('/audio', buildAudioRoutes(io));
  api.use('/voice', voiceRoutes);
  api.use('/music-research', musicResearchRoutes);
  api.use('/chat', chatRoutes);
  api.use('/album-discovery', albumDiscoveryRoutes);
  api.use('/tree-discovery', treeDiscoveryRoutes);
  api.use('/tree-collection', treeCollectionRoutes);
  api.use('/critter-discovery', critterDiscoveryRoutes);
  api.use('/critter-collection', critterCollectionRoutes);
  api.use('/nature-collection', natureCollectionRoutes);
  api.use('/blacklight', blacklightRoutes);
  api.use('/ouija-board', ouijaBoardRoutes);
  api.use('/spotify', spotifyRoutes);
  api.use('/collection', collectionRoutes);
  api.use('/genealogy', genealogyRoutes);
  api.use('/poster-generator', posterGeneratorRoutes);
  api.use('/voice-dj', voiceDjRoutes);
  api.use('/audio-fingerprint', audioFingerprintRoutes);
  api.use('/sample-detection', sampleDetectionRoutes);
  api.use('/encompass', encompassAssistantRoutes);
  api.use('/kml', kmlRoutes);
  api.use('/grateful-dead', gratefulDeadTourRoutes);
  api.use('/music-pilgrimage', musicPilgrimageRoutes);
  api.use('/user-attendance', userShowAttendanceRoutes);
  api.use('/concert-collection', concertCollectionRoutes);
  api.use('/loan-pipeline', loanPipelineRoutes);
  api.use('/encompass-hub', encompassHubRoutes);
  api.use('/disasters', disastersRoutes);
  api.use('/webhooks', encompassWebhookRoutes);
  api.use('/fish-catches', fishCatchesRoutes);
  api.use('/rock-discovery', rockDiscoveryRoutes);
  api.use('/rock-specimens', rockCollectionRoutes);
  api.use('/bikes', bikesRoutes);
  api.use('/customers', customersRoutes);
  api.use('/unit-tests', unitTestsRoutes);
  api.use('/reviewer', reviewerRoutes);
  api.use('/local-spots', localSpotsRoutes);
  api.use('/finds', findsRoutes);
  api.use('/auth', appUserAuthRoutes);
  api.use('/gse', gseRoutes);
  api.use('/finance', financeRoutes);
  api.use('/disaster-impact-graph', disasterImpactGraphRoutes);
  api.use('/', musicHistoryRoutes); // Music history and concert finder
  return api;
}