/**
 * Development work by David Lane
 *
 * Allowlisted ICE Developer Connect operations for Enhanced Conditions.
 * Paths are templates only — invoke substitutes {params} and never accepts a free-form URL.
 */
function op(entry) {
  const method = String(entry.method || 'GET').toUpperCase();
  const pathParams = [...(entry.path.matchAll(/\{([^}]+)\}/g) || [])].map((m) => m[1]);
  return {
    destructive: method !== 'GET',
    pathParams,
    queryKeys: [],
    defaultQuery: {},
    sampleBody: null,
    notes: '',
    action: 'list',
    ...entry,
    method,
    pathParams: entry.pathParams || pathParams,
  };
}

export const CONDITIONS_CATALOG = [
  op({
    id: 'ec.types.list',
    group: 'Condition types',
    name: 'List condition types',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/settings/loan/conditions/types',
    queryKeys: ['view', 'start', 'limit'],
  }),
  op({
    id: 'ec.types.get',
    group: 'Condition types',
    name: 'Get condition type',
    action: 'get',
    method: 'GET',
    path: '/encompass/v3/settings/loan/conditions/types/{typeId}',
    queryKeys: ['view'],
    idParam: 'typeId',
  }),
  op({
    id: 'ec.types.create',
    group: 'Condition types',
    name: 'Create condition types',
    action: 'create',
    method: 'PATCH',
    path: '/encompass/v3/settings/loan/conditions/types',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'add', view: 'entity' },
    sampleBody: [
      {
        title: 'Pre-Purchase',
        definitions: {
          categoryDefinitions: [{ title: 'Credit' }],
          recipientDefinitions: [{ title: 'Borrower / TPO' }],
          sourceDefinitions: [{ title: 'Underwriting' }],
          priorToDefinitions: [{ title: 'Prior to Docs' }],
          trackingDefinitions: [{ title: 'Received' }],
        },
      },
    ],
    notes: 'Create types before templates. Body is a JSON array.',
  }),
  op({
    id: 'ec.types.update',
    group: 'Condition types',
    name: 'Update / activate condition types',
    action: 'update',
    method: 'PATCH',
    path: '/encompass/v3/settings/loan/conditions/types',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'update', view: 'entity' },
    sampleBody: [{ id: '', active: true }],
  }),
  op({
    id: 'ec.types.delete',
    group: 'Condition types',
    name: 'Delete condition types',
    action: 'delete',
    method: 'PATCH',
    path: '/encompass/v3/settings/loan/conditions/types',
    queryKeys: ['action', 'templateOption', 'view'],
    defaultQuery: { action: 'delete', templateOption: 'delete', view: 'entity' },
    sampleBody: [{ id: '' }],
  }),
  op({
    id: 'ec.templates.list',
    group: 'Condition templates',
    name: 'List condition templates',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/settings/loan/conditions/templates',
    queryKeys: ['view', 'start', 'limit'],
  }),
  op({
    id: 'ec.templates.get',
    group: 'Condition templates',
    name: 'Get condition template',
    action: 'get',
    method: 'GET',
    path: '/encompass/v3/settings/loan/conditions/templates/{templateId}',
    queryKeys: ['view'],
    idParam: 'templateId',
  }),
  op({
    id: 'ec.templates.create',
    group: 'Condition templates',
    name: 'Create condition templates',
    action: 'create',
    method: 'PATCH',
    path: '/encompass/v3/settings/loan/conditions/templates',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'add', view: 'entity' },
    sampleBody: [
      {
        title: 'Provide notice of value',
        conditionType: 'Pre-Purchase',
        internalId: 'ABC01',
        internalDescription: 'Sample template',
        category: 'Credit',
        source: 'Underwriting',
        priorTo: 'Prior to Docs',
        recipient: 'Borrower / TPO',
        printDefinitions: ['InternalPrint'],
      },
    ],
    notes: 'Types must exist first. Smoke-test a small batch before bulk loads.',
  }),
  op({
    id: 'ec.templates.update',
    group: 'Condition templates',
    name: 'Update condition templates',
    action: 'update',
    method: 'PATCH',
    path: '/encompass/v3/settings/loan/conditions/templates',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'update', view: 'entity' },
    sampleBody: [{ id: '', title: 'Updated title' }],
  }),
  op({
    id: 'ec.sets.list',
    group: 'Condition sets',
    name: 'List condition sets',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/settings/loan/conditions/sets',
    queryKeys: ['view'],
  }),
  op({
    id: 'ec.sets.get',
    group: 'Condition sets',
    name: 'Get condition set',
    action: 'get',
    method: 'GET',
    path: '/encompass/v3/settings/loan/conditions/sets/{setId}',
    queryKeys: ['view'],
    idParam: 'setId',
  }),
  op({
    id: 'ec.loan.list',
    group: 'Loan conditions',
    name: 'List loan conditions',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/loans/{loanId}/conditions',
    queryKeys: ['view'],
    idParam: 'loanId',
  }),
  op({
    id: 'ec.loan.add',
    group: 'Loan conditions',
    name: 'Add loan conditions',
    action: 'create',
    method: 'PATCH',
    path: '/encompass/v3/loans/{loanId}/conditions',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'add', view: 'entity' },
    idParam: 'loanId',
    sampleBody: [{ title: 'Sample condition', conditionType: { id: '' } }],
  }),
  op({
    id: 'ec.loan.update',
    group: 'Loan conditions',
    name: 'Update loan conditions',
    action: 'update',
    method: 'PATCH',
    path: '/encompass/v3/loans/{loanId}/conditions',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'update', view: 'entity' },
    idParam: 'loanId',
    sampleBody: [{ id: '', status: 'Received' }],
  }),
  op({
    id: 'ec.loan.remove',
    group: 'Loan conditions',
    name: 'Remove loan conditions',
    action: 'delete',
    method: 'PATCH',
    path: '/encompass/v3/loans/{loanId}/conditions',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'remove', view: 'entity' },
    idParam: 'loanId',
    sampleBody: [{ id: '' }],
  }),
  op({
    id: 'ec.loan.duplicate',
    group: 'Loan conditions',
    name: 'Duplicate loan conditions',
    action: 'create',
    method: 'PATCH',
    path: '/encompass/v3/loans/{loanId}/conditions',
    queryKeys: ['action', 'view'],
    defaultQuery: { action: 'duplicate', view: 'entity' },
    idParam: 'loanId',
    sampleBody: [{ id: '' }],
  }),
  op({
    id: 'ec.loan.comments.list',
    group: 'Loan condition details',
    name: 'List condition comments',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/loans/{loanId}/conditions/{conditionId}/comments',
    pathParams: ['loanId', 'conditionId'],
  }),
  op({
    id: 'ec.loan.comments.add',
    group: 'Loan condition details',
    name: 'Add condition comment',
    action: 'create',
    method: 'POST',
    path: '/encompass/v3/loans/{loanId}/conditions/{conditionId}/comments',
    pathParams: ['loanId', 'conditionId'],
    sampleBody: { comments: 'Followed up with TPO.' },
  }),
  op({
    id: 'ec.loan.tracking.get',
    group: 'Loan condition details',
    name: 'Get condition tracking',
    action: 'get',
    method: 'GET',
    path: '/encompass/v3/loans/{loanId}/conditions/{conditionId}/tracking',
    pathParams: ['loanId', 'conditionId'],
  }),
  op({
    id: 'ec.loan.tracking.update',
    group: 'Loan condition details',
    name: 'Update condition tracking',
    action: 'update',
    method: 'PATCH',
    path: '/encompass/v3/loans/{loanId}/conditions/{conditionId}/tracking',
    pathParams: ['loanId', 'conditionId'],
    sampleBody: {},
  }),
  op({
    id: 'ec.loan.documents.list',
    group: 'Loan condition details',
    name: 'List condition documents',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/loans/{loanId}/conditions/{conditionId}/documents',
    pathParams: ['loanId', 'conditionId'],
  }),
  op({
    id: 'ec.loan.documents.update',
    group: 'Loan condition details',
    name: 'Update condition documents',
    action: 'update',
    method: 'PATCH',
    path: '/encompass/v3/loans/{loanId}/conditions/{conditionId}/documents',
    pathParams: ['loanId', 'conditionId'],
    sampleBody: [],
  }),
  op({
    id: 'ec.automated.evaluate',
    group: 'Automation',
    name: 'Evaluate automated conditions',
    action: 'create',
    method: 'POST',
    path: '/encompass/v3/calculators/automatedConditions',
    queryKeys: ['loanId'],
    sampleBody: {},
  }),
  op({
    id: 'ec.personas.list',
    group: 'Personas',
    name: 'List personas (ACL reconciliation)',
    action: 'list',
    method: 'GET',
    path: '/encompass/v3/settings/personas',
    queryKeys: ['start', 'limit'],
  }),
];

export const CATALOGS = {
  conditions: CONDITIONS_CATALOG,
};

export function getCatalog(domain) {
  return CATALOGS[domain] || null;
}

export function findOperation(domain, operationId) {
  const catalog = getCatalog(domain);
  if (!catalog) return null;
  return catalog.find((item) => item.id === operationId) || null;
}
